# Generated by Django 5.0.2 on 2024-02-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.ingredient'),
        ),
        migrations.DeleteModel(
            name='IngredientThroughRecipe',
        ),
    ]
